### ISSUE TITLE
2.11.0: Still doesn’t show the Dictionary view

### ISSUE THREAD

**Issue by Moonbase59** [phibr0/obsidian-dictionary#28]
title says it, just testing the new release

![Knowledgebase - Obsidian v0 12 10_062](https://user-images.githubusercontent.com/3706922/126879341-d47342db-8959-48b8-a1f8-71cb8e2eadc3.png)

_Did_ close the pane and reopened it using cmd palette. Also restarted Obsidian after update.

Are there any changes in `data.json`? When upgrading from 2.10.0 to 2.11.0, this still contains my old cached definitions, so I assume it is merged somehow or left undisturbed? `cache.json` was created, though. Think I should uninstall/reinstall?

**Comment by Moonbase59** [comment]
Dev console output:

```text
app.js:1 Obsidian Developer Console
main.ts:27 loading markdown-table-editor plugin
main.ts:38 Dataview: Version 0.4.x Loaded
main.ts:60 DiceRoller plugin loaded
main.ts:49 loading Find unlinked files and unresolved links plugin
main.ts:40 loading Hotkeys for templates plugin v1.4.1
main.ts:10 Loading Hotkeys++ plugin
main.ts:125 loading plugin
VM135:2 Loading Obsidian Leaflet v3.20.2
main.ts:45 loading plugin
main.ts:40 loading sortable plugin
main.ts:17 Loading snippets plugin
main.ts:27 Loading Pandoc plugin
VM148:4165 loading dictionary
main.ts:26 Loading status bar pomo timer...
app.js:1 Failed to open view TypeError: _a.getElementById is not a function
    at append_styles (eval at <anonymous> (app.js:1), <anonymous>:540:75)
    at add_css$1 (eval at <anonymous> (app.js:1), <anonymous>:2305:2)
    at init (eval at <anonymous> (app.js:1), <anonymous>:1015:22)
    at new DictionaryView$1 (eval at <anonymous> (app.js:1), <anonymous>:2944:3)
    at DictionaryView.onOpen (eval at <anonymous> (app.js:1), <anonymous>:3073:22)
    at DictionaryView.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
(anonymous) @ app.js:1
index.ts:355 Dataview: Parsed all file prefixes (0.001s)
main.ts:148 Hotkeys for templates -> active plugins: templater-obsidian,core
index.ts:246 Dataview: Task & metadata parsing queued in 0s.
VM148:3069 Uncaught (in promise) TypeError: Cannot read property '$destroy' of undefined
    at DictionaryView.onClose (eval at <anonymous> (app.js:1), <anonymous>:3069:20)
    at DictionaryView.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
    at o (app.js:1)
    at DictionaryView.t.close (app.js:1)
    at t.detach (app.js:1)
    at app.js:1
app.js:1 Failed to open view TypeError: _a.getElementById is not a function
    at append_styles (eval at <anonymous> (app.js:1), <anonymous>:540:75)
    at add_css$1 (eval at <anonymous> (app.js:1), <anonymous>:2305:2)
    at init (eval at <anonymous> (app.js:1), <anonymous>:1015:22)
    at new DictionaryView$1 (eval at <anonymous> (app.js:1), <anonymous>:2944:3)
    at DictionaryView.onOpen (eval at <anonymous> (app.js:1), <anonymous>:3073:22)
    at DictionaryView.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at app.js:1
    at new Promise (<anonymous>)
(anonymous) @ app.js:1
DevTools failed to load SourceMap: Could not parse content for app://obsidian.md/main.js.map: Unexpected end of JSON input
```

**Comment by phibr0** [comment]
Yeah the old cache still persists, I would do a clean reinstall, but I will probably also clear it in a future release.

Again here, how did you install the Update?

**Comment by phibr0** [comment]
Lets further track this in #24
